name: Deploy to GCP Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: pdo_mysql, intl, mbstring
        tools: composer

    - name: Install Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Deploy to Deploy Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: "./"
        REMOTE_HOST: "35.207.217.200"
        REMOTE_USER: "deployer"
        TARGET: "/var/www/inventory"
